"""Competition-safe GUI that does not use VTK/OpenGL for the main 3D display.

The measurement/reconstruction pipeline is unchanged.  The central visualization is a
CPU-rendered perspective projection drawn with NumPy/OpenCV and shown in a QLabel.
This avoids GPU-driver / OpenGL actor rendering issues on competition laptops.
"""
from __future__ import annotations

import os
import sys
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
from PySide6.QtCore import Qt
from PySide6.QtGui import QImage, QPixmap
from PySide6.QtWidgets import (
    QApplication, QComboBox, QDialog, QDoubleSpinBox, QFileDialog, QFormLayout,
    QGridLayout, QGroupBox, QLabel, QLineEdit, QMainWindow, QMessageBox,
    QPushButton, QSplitter, QTabWidget, QTextEdit, QVBoxLayout, QWidget,
)

from history_manager import append_history, read_recent_history
from measurement_analysis import analyze_groove
from measurement_task import MeasurementTask
from offline_reconstruction import imread_unicode, reconstruct_directory
from report_generator import generate_measurement_report

ROOT = Path(sys.executable).resolve().parent if getattr(sys, "frozen", False) else Path(__file__).resolve().parent
OUTPUT_ROOT = ROOT / "outputs"
DATA_ROOT = ROOT / "示例数据"
HISTORY_PATH = OUTPUT_ROOT / "history" / "measurement_history.csv"


def load_point_cloud(path: Path) -> np.ndarray:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        frame = pd.read_csv(path)
        if {"x", "y", "z"}.issubset(frame.columns):
            return frame[["x", "y", "z"]].to_numpy(float)
        if frame.shape[1] >= 3:
            return frame.iloc[:, :3].to_numpy(float)
        raise ValueError("CSV 至少需要三列或 x、y、z 三列")
    if suffix in {".xyz", ".txt"}:
        data = np.loadtxt(path, dtype=float)
        if data.ndim != 2 or data.shape[1] < 3:
            raise ValueError("XYZ/TXT 点云至少需要三列")
        return data[:, :3]
    raise ValueError("安全版为避免 VTK 依赖，仅支持 CSV / XYZ / TXT 点云。")


def array_to_pixmap(image: np.ndarray, target: QLabel) -> QPixmap:
    if image.ndim == 2:
        rgb = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
    else:
        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    rgb = np.ascontiguousarray(rgb)
    h, w, c = rgb.shape
    qimg = QImage(rgb.data, w, h, w * c, QImage.Format_RGB888).copy()
    return QPixmap.fromImage(qimg).scaled(target.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)


def render_cpu_projection(points: np.ndarray, width: int = 1080, height: int = 720) -> np.ndarray:
    """Render a stable pseudo-3D perspective image using CPU only (no OpenGL)."""
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] < 3 or pts.shape[0] < 3:
        raise ValueError("点云数据无效")

    # Deterministic downsample for display only; analysis always uses the full cloud.
    max_display = 95000
    if pts.shape[0] > max_display:
        stride = int(np.ceil(pts.shape[0] / max_display))
        draw_pts = pts[::stride].copy()
    else:
        draw_pts = pts.copy()

    # Center and normalize visual aspect.  Y is physically much longer than the transverse
    # section, so compress it only for visualization, similar to an interactive 3D camera.
    xyz = draw_pts[:, :3].copy()
    center = np.nanmedian(xyz, axis=0)
    xyz -= center
    ranges = np.ptp(xyz, axis=0)
    xr = max(ranges[0], 1e-9)
    yr = max(ranges[1], 1e-9)
    zr = max(ranges[2], 1e-9)
    xyz[:, 1] *= (xr / yr) * 2.55
    xyz[:, 2] *= (xr / zr) * 0.82

    # Fixed competition-friendly isometric-like view.
    yaw = np.deg2rad(-34.0)
    pitch = np.deg2rad(58.0)
    rz = np.array([[np.cos(yaw), -np.sin(yaw), 0.0],
                   [np.sin(yaw),  np.cos(yaw), 0.0],
                   [0.0, 0.0, 1.0]])
    rx = np.array([[1.0, 0.0, 0.0],
                   [0.0, np.cos(pitch), -np.sin(pitch)],
                   [0.0, np.sin(pitch),  np.cos(pitch)]])
    rot = xyz @ (rx @ rz).T
    u = rot[:, 0]
    v = -rot[:, 2]

    canvas = np.zeros((height, width, 3), dtype=np.uint8)
    canvas[:] = (24, 31, 38)

    # Fit the projected cloud into the canvas.
    margin_x, margin_y = 70, 65
    ur = max(float(np.ptp(u)), 1e-9)
    vr = max(float(np.ptp(v)), 1e-9)
    scale = min((width - 2 * margin_x) / ur, (height - 2 * margin_y) / vr)
    px = ((u - u.min()) * scale + margin_x).astype(np.int32)
    py = ((v - v.min()) * scale + margin_y).astype(np.int32)

    # Height colors, generated by OpenCV on CPU.
    z = draw_pts[:, 2]
    zmin, zmax = float(np.nanmin(z)), float(np.nanmax(z))
    zn = ((z - zmin) / max(zmax - zmin, 1e-9) * 255.0).clip(0, 255).astype(np.uint8)
    colors = cv2.applyColorMap(zn.reshape(-1, 1), cv2.COLORMAP_TURBO).reshape(-1, 3)

    # Draw points from back to front for a more readable surface.
    order = np.argsort(rot[:, 1])
    for idx in order:
        x, y = int(px[idx]), int(py[idx])
        if 0 <= x < width and 0 <= y < height:
            c = tuple(int(vv) for vv in colors[idx])
            cv2.circle(canvas, (x, y), 1, c, -1, lineType=cv2.LINE_AA)

    # Draw representative cross-section polylines as an independent, very visible layer.
    full = np.asarray(points[:, :3], dtype=float)
    rounded_y = np.round(full[:, 1], 6)
    unique_y = np.unique(rounded_y)
    stride_y = max(1, len(unique_y) // 34)
    for y_value in unique_y[::stride_y]:
        sec = full[rounded_y == y_value]
        if sec.shape[0] < 3:
            continue
        sec = sec[np.argsort(sec[:, 0])]
        sec_vis = sec.copy()
        sec_vis[:, :3] -= center
        sec_vis[:, 1] *= (xr / yr) * 2.55
        sec_vis[:, 2] *= (xr / zr) * 0.82
        srot = sec_vis @ (rx @ rz).T
        su = ((srot[:, 0] - u.min()) * scale + margin_x).astype(np.int32)
        sv = ((-srot[:, 2] - v.min()) * scale + margin_y).astype(np.int32)
        poly = np.column_stack([su, sv]).reshape(-1, 1, 2)
        cv2.polylines(canvas, [poly], False, (55, 105, 255), 1, cv2.LINE_AA)

    # Labels deliberately say "CPU兼容投影" so it is clear why this view is stable.
    cv2.putText(canvas, "CPU Safe 3D Projection", (28, 34), cv2.FONT_HERSHEY_SIMPLEX, 0.78, (230, 238, 245), 2, cv2.LINE_AA)
    cv2.putText(canvas, f"Points: {points.shape[0]}   Z range: {zmin:.3f} ~ {zmax:.3f} mm", (28, height - 24), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (170, 190, 205), 1, cv2.LINE_AA)
    return canvas


class SafeMainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("槽型深度宽度测量软件 | 比赛安全版（无 OpenGL）")
        self.resize(1680, 980)
        self.task = self.reconstruction = self.result = self.points = self.last_report = None
        self._build_ui()
        self._apply_style()
        self.apply_task()
        self.log("安全模式已启用：三维展示采用 CPU 投影，不依赖 VTK/OpenGL。推荐直接点击“一键安全演示”。")

    def _build_ui(self):
        root = QWidget(self)
        layout = QVBoxLayout(root)
        layout.setContentsMargins(8, 8, 8, 8)
        title = QLabel("槽型深度宽度测量软件")
        title.setObjectName("title")
        subtitle = QLabel("比赛安全版 · 一键案例 · 离线点云重建 · CPU三维兼容投影 · 槽深槽宽分析 · PDF报告")
        subtitle.setObjectName("subtitle")
        layout.addWidget(title)
        layout.addWidget(subtitle)
        splitter = QSplitter(Qt.Horizontal)
        splitter.addWidget(self._build_task_panel())
        splitter.addWidget(self._build_viewer_panel())
        splitter.addWidget(self._build_result_panel())
        splitter.setSizes([320, 970, 390])
        layout.addWidget(splitter, 1)
        self.console = QTextEdit()
        self.console.setReadOnly(True)
        self.console.setMaximumHeight(140)
        layout.addWidget(self.console)
        self.setCentralWidget(root)

    def _build_task_panel(self):
        panel = QWidget(); panel.setMinimumWidth(295)
        outer = QVBoxLayout(panel)
        group = QGroupBox("测量任务设置")
        form = QFormLayout(group)
        self.sample_id = QLineEdit("DEMO-V-001")
        self.groove_type = QComboBox(); self.groove_type.addItems(["直线 V 型槽", "环形槽", "十字槽", "球弧面槽"])
        self.data_nature = QComboBox(); self.data_nature.addItems(["图像序列数据", "外部点云"])
        self.target_depth = QDoubleSpinBox(); self.target_depth.setRange(0.0001,1000); self.target_depth.setDecimals(4); self.target_depth.setValue(0.6000)
        self.target_width = QDoubleSpinBox(); self.target_width.setRange(0.0001,1000); self.target_width.setDecimals(4); self.target_width.setValue(0.8500)
        self.tolerance = QDoubleSpinBox(); self.tolerance.setRange(0.0001,100); self.tolerance.setDecimals(4); self.tolerance.setValue(0.0200)
        self.operator = QLineEdit("")
        self.notes = QLineEdit("比赛安全模式")
        for a,b in [("样本编号",self.sample_id),("槽型",self.groove_type),("数据性质",self.data_nature),("标准槽深/mm",self.target_depth),("标准槽宽/mm",self.target_width),("允许误差/mm",self.tolerance),("操作人员",self.operator),("备注",self.notes)]:
            form.addRow(a,b)
        outer.addWidget(group)

        safe = QPushButton("一键安全演示（推荐）")
        safe.setObjectName("safe")
        safe.setToolTip("直接载入预生成点云与预览图，速度最快、最不依赖电脑图形环境")
        safe.clicked.connect(self.run_safe_demo)
        full = QPushButton("一键完整重建（181帧）")
        full.setObjectName("primary")
        full.clicked.connect(self.run_full_demo)
        apply_button = QPushButton("应用任务参数"); apply_button.clicked.connect(self.apply_task)
        image_button = QPushButton("选择原始图片目录"); image_button.clicked.connect(self.select_image_directory)
        cloud_button = QPushButton("导入点云文件（CSV/XYZ）"); cloud_button.clicked.connect(self.import_point_cloud)
        analyze_button = QPushButton("重新分析当前点云"); analyze_button.clicked.connect(self.analyze_current)
        for b in [safe, full, apply_button, image_button, cloud_button, analyze_button]:
            outer.addWidget(b)
        hint = QLabel("比赛建议：优先使用“一键安全演示”。\n该模式不使用 VTK/OpenGL，不要求更新显卡驱动。")
        hint.setWordWrap(True); hint.setObjectName("hint"); outer.addWidget(hint); outer.addStretch(1)
        return panel

    def _build_viewer_panel(self):
        panel = QWidget(); layout = QVBoxLayout(panel)
        group = QGroupBox("三维点云与槽型结果（CPU兼容投影）")
        gl = QVBoxLayout(group)
        self.viewer_label = QLabel("点击“一键安全演示”开始")
        self.viewer_label.setAlignment(Qt.AlignCenter)
        self.viewer_label.setMinimumSize(720, 520)
        self.viewer_label.setStyleSheet("background:#12171d;border:1px solid #3a4650;")
        gl.addWidget(self.viewer_label)
        layout.addWidget(group)
        return panel

    def _build_result_panel(self):
        panel = QWidget(); panel.setMinimumWidth(360); outer = QVBoxLayout(panel)
        group = QGroupBox("测量结果"); form = QFormLayout(group)
        keys = ["槽深均值","槽宽均值","槽深均值判定","槽宽均值判定","槽深最小值及位置","槽深最大值及位置","槽宽最小值及位置","槽宽最大值及位置","有效截面","点云点数","读取/重建耗时","分析耗时"]
        self.result_labels = {}
        for key in keys:
            label = QLabel("—"); label.setWordWrap(True); self.result_labels[key] = label; form.addRow(key,label)
        outer.addWidget(group)
        self.tabs = QTabWidget(); self.image_labels = {}
        for name in ["原始图像","中心提取","二值掩膜"]:
            label = QLabel("演示后显示"); label.setAlignment(Qt.AlignCenter); label.setMinimumHeight(190); label.setStyleSheet("background:#10151a;border:1px solid #3a4650;")
            self.image_labels[name] = label; self.tabs.addTab(label,name)
        outer.addWidget(self.tabs)
        grid = QGridLayout()
        rb = QPushButton("生成 PDF 报告"); rb.setObjectName("primary"); rb.clicked.connect(self.generate_report)
        hb = QPushButton("查看历史记录"); hb.clicked.connect(self.show_history)
        ob = QPushButton("打开输出结果"); ob.clicked.connect(self.show_output_path)
        grid.addWidget(rb,0,0,1,2); grid.addWidget(hb,1,0); grid.addWidget(ob,1,1); outer.addLayout(grid)
        return panel

    def _apply_style(self):
        self.setStyleSheet("QMainWindow,QWidget{background:#1b2229;color:#e7eef5;font-family:'Microsoft YaHei UI';font-size:10pt;} QLabel#title{font-size:22pt;font-weight:700;color:white;padding:3px;} QLabel#subtitle{color:#9fb1bf;padding:0 3px 6px 3px;} QLabel#hint{color:#9fb1bf;padding:8px 2px;} QGroupBox{border:1px solid #3a4650;border-radius:7px;margin-top:12px;padding-top:10px;font-weight:600;} QGroupBox::title{subcontrol-origin:margin;left:12px;padding:0 5px;color:#78e3d7;} QLineEdit,QComboBox,QDoubleSpinBox,QTextEdit,QTabWidget::pane{background:#11171c;border:1px solid #3a4650;border-radius:4px;padding:5px;} QPushButton{background:#2b3640;border:1px solid #4b5b67;border-radius:5px;padding:8px;} QPushButton:hover{background:#374550;} QPushButton#primary{background:#007f78;border-color:#00b7aa;font-weight:700;} QPushButton#safe{background:#0b8f68;border:2px solid #63efb5;font-weight:800;font-size:11pt;padding:11px;} QTabBar::tab{background:#242e37;padding:7px;} QTabBar::tab:selected{background:#007f78;}")

    def log(self, message):
        self.console.append(f"[{datetime.now().strftime('%H:%M:%S')}] {message}")

    def apply_task(self):
        try:
            self.task = MeasurementTask(sample_id=self.sample_id.text().strip() or "UNNAMED", groove_type=self.groove_type.currentText(), data_nature=self.data_nature.currentText(), target_depth_mm=self.target_depth.value(), target_width_mm=self.target_width.value(), tolerance_mm=self.tolerance.value(), operator=self.operator.text().strip(), notes=self.notes.text().strip())
            self.log(f"已应用任务：{self.task.sample_id}，槽深 {self.task.target_depth_mm:.4f} mm，槽宽 {self.task.target_width_mm:.4f} mm，公差 ±{self.task.tolerance_mm:.4f} mm。")
        except Exception as exc:
            QMessageBox.critical(self, "任务参数错误", str(exc))

    def run_safe_demo(self):
        """Fastest path: pre-generated point cloud + pre-generated image previews."""
        cloud_path = DATA_ROOT / "03_外部点云" / "181帧_紧凑曲面V槽点云.csv"
        preview_root = DATA_ROOT / "04_安全演示预览"
        if not cloud_path.exists():
            QMessageBox.critical(self, "安全案例缺失", f"未找到：\n{cloud_path}\n\n请完整解压整个软件目录。")
            return
        try:
            self.sample_id.setText("DEMO-V-SAFE")
            self.data_nature.setCurrentText("外部点云")
            self.notes.setText("比赛安全模式：预生成点云 + CPU投影")
            self.apply_task()
            self.log("正在载入一键安全案例……")
            self.points = load_point_cloud(cloud_path)
            self.reconstruction = {
                "points": self.points, "source_dir": str(cloud_path.parent), "point_cloud_csv": str(cloud_path),
                "original_frames": 181, "valid_frames": 181, "point_count": int(self.points.shape[0]),
                "read_seconds": 0.0, "calibration_applied": False,
                "preview_original": str(preview_root / "original.png"),
                "preview_overlay": str(preview_root / "center_overlay.png"),
                "preview_mask": str(preview_root / "binary_mask.png"),
            }
            self.result = analyze_groove(self.points)
            self.render_points(); self.update_images(); self.update_results()
            self.log(f"安全案例完成：181 个有效截面，点云 {self.points.shape[0]} 点。三维图采用 CPU 投影。")
        except Exception as exc:
            self.log(f"安全案例失败：{exc}")
            QMessageBox.critical(self, "安全案例失败", str(exc))

    def run_full_demo(self):
        directory = DATA_ROOT / "01_原始图像_181帧_紧凑曲面V槽"
        if not directory.exists():
            QMessageBox.critical(self, "内置图像案例缺失", f"未找到：\n{directory}")
            return
        self.data_nature.setCurrentText("图像序列数据")
        self.notes.setText("比赛完整重建演示")
        self.apply_task()
        try:
            self._run_image_directory(directory)
        except Exception as exc:
            QMessageBox.critical(self, "重建失败", str(exc))

    def select_image_directory(self):
        directory = QFileDialog.getExistingDirectory(self, "选择原始激光图片目录", str(DATA_ROOT if DATA_ROOT.exists() else ROOT))
        if not directory: return
        self.data_nature.setCurrentText("图像序列数据"); self.apply_task()
        try: self._run_image_directory(Path(directory))
        except Exception as exc: QMessageBox.critical(self, "重建失败", str(exc)); self.log(f"重建失败：{exc}")

    def _run_image_directory(self, directory: Path):
        session = OUTPUT_ROOT / "offline_reconstruction" / f"{self.task.sample_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        self.log(f"开始读取图像序列：{directory}")
        self.reconstruction = reconstruct_directory(directory, session)
        self.points = self.reconstruction["points"]
        self.result = analyze_groove(self.points)
        self.render_points(); self.update_images(); self.update_results()
        self.log(f"处理完成：{self.reconstruction['valid_frames']}/{self.reconstruction['original_frames']} 帧有效，点云 {self.reconstruction['point_count']} 点。")

    def import_point_cloud(self):
        filename, _ = QFileDialog.getOpenFileName(self, "导入点云文件", str(DATA_ROOT if DATA_ROOT.exists() else ROOT), "Point Cloud (*.csv *.xyz *.txt)")
        if not filename: return
        try:
            self.data_nature.setCurrentText("外部点云"); self.apply_task()
            self.points = load_point_cloud(Path(filename))
            self.reconstruction = {"points":self.points,"source_dir":str(Path(filename).parent),"point_cloud_csv":filename,"original_frames":0,"valid_frames":0,"point_count":int(self.points.shape[0]),"read_seconds":0.0,"calibration_applied":False,"preview_original":"","preview_overlay":"","preview_mask":""}
            self.result = analyze_groove(self.points)
            self.render_points(); self.update_results(); self.log(f"已导入点云：{filename}，共 {self.points.shape[0]} 点。")
        except Exception as exc:
            QMessageBox.critical(self, "导入失败", str(exc))

    def analyze_current(self):
        if self.points is None:
            QMessageBox.information(self, "提示", "请先运行案例或导入点云文件。")
            return
        try:
            self.result = analyze_groove(self.points); self.update_results(); self.render_points(); self.log("当前点云重新分析完成。")
        except Exception as exc:
            QMessageBox.critical(self, "分析失败", str(exc))

    def render_points(self):
        if self.points is None: return
        image = render_cpu_projection(self.points, 1080, 720)
        self.viewer_label.setPixmap(array_to_pixmap(image, self.viewer_label))
        self.viewer_label.setToolTip("CPU 兼容投影：不使用 VTK/OpenGL；数值分析仍基于完整三维点云。")

    def update_images(self):
        if not self.reconstruction: return
        paths = {"原始图像":self.reconstruction.get("preview_original"),"中心提取":self.reconstruction.get("preview_overlay"),"二值掩膜":self.reconstruction.get("preview_mask")}
        for name, path in paths.items():
            if path and Path(path).exists():
                image = imread_unicode(path, cv2.IMREAD_UNCHANGED)
                if image is not None: self.image_labels[name].setPixmap(array_to_pixmap(image, self.image_labels[name]))

    def update_results(self):
        if not self.result or not self.reconstruction or not self.task: return
        depth_ok = abs(self.result.depth_mean-self.task.target_depth_mm) <= self.task.tolerance_mm
        width_ok = abs(self.result.width_mean-self.task.target_width_mm) <= self.task.tolerance_mm
        values = {
            "槽深均值":f"{self.result.depth_mean:.4f} mm", "槽宽均值":f"{self.result.width_mean:.4f} mm",
            "槽深均值判定":"合格" if depth_ok else "超差", "槽宽均值判定":"合格" if width_ok else "超差",
            "槽深最小值及位置":f"{self.result.depth_min:.4f} mm @ Y={self.result.depth_min_y:.3f}",
            "槽深最大值及位置":f"{self.result.depth_max:.4f} mm @ Y={self.result.depth_max_y:.3f}",
            "槽宽最小值及位置":f"{self.result.width_min:.4f} mm @ Y={self.result.width_min_y:.3f}",
            "槽宽最大值及位置":f"{self.result.width_max:.4f} mm @ Y={self.result.width_max_y:.3f}",
            "有效截面":str(len(self.result.sections)), "点云点数":str(self.reconstruction.get("point_count",0)),
            "读取/重建耗时":f"{self.reconstruction.get('read_seconds',0):.3f} s", "分析耗时":f"{self.result.analysis_seconds:.3f} s",
        }
        for k,v in values.items(): self.result_labels[k].setText(v)
        for k in ["槽深均值判定","槽宽均值判定"]:
            self.result_labels[k].setStyleSheet("color:#65e58a;font-weight:700;" if self.result_labels[k].text()=="合格" else "color:#ff7373;font-weight:700;")

    def generate_report(self):
        if not self.task or not self.reconstruction or not self.result:
            QMessageBox.information(self,"提示","请先完成一次测量分析。")
            return
        report_path = OUTPUT_ROOT / "reports" / datetime.now().strftime("%Y-%m-%d") / f"{self.task.sample_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}_measurement_report.pdf"
        try:
            self.last_report, report_seconds = generate_measurement_report(self.task,self.reconstruction,self.result,report_path)
            ds = "合格" if abs(self.result.depth_mean-self.task.target_depth_mm)<=self.task.tolerance_mm else "超差"
            ws = "合格" if abs(self.result.width_mean-self.task.target_width_mm)<=self.task.tolerance_mm else "超差"
            append_history(HISTORY_PATH,{"sample_id":self.task.sample_id,"groove_type":self.task.groove_type,"data_nature":self.task.data_nature,"target_depth_mm":self.task.target_depth_mm,"measured_depth_mm":self.result.depth_mean,"target_width_mm":self.task.target_width_mm,"measured_width_mm":self.result.width_mean,"tolerance_mm":self.task.tolerance_mm,"depth_status":ds,"width_status":ws,"point_count":self.reconstruction.get("point_count",0),"valid_sections":len(self.result.sections),"read_seconds":self.reconstruction.get("read_seconds",0),"analysis_seconds":self.result.analysis_seconds,"report_seconds":report_seconds,"report_path":str(self.last_report)})
            QMessageBox.information(self,"报告生成成功","测量报告已保存至输出结果目录。")
            self.log(f"PDF 报告已生成：{self.last_report}")
        except Exception as exc:
            QMessageBox.critical(self,"报告生成失败",str(exc))

    def show_history(self):
        rows = read_recent_history(HISTORY_PATH,20)
        dialog = QDialog(self); dialog.setWindowTitle("最近测量历史"); dialog.resize(1000,520)
        layout = QVBoxLayout(dialog); text = QTextEdit(); text.setReadOnly(True)
        text.setPlainText("\n".join(f"{r.get('timestamp')} | {r.get('sample_id')} | 槽深均值 {r.get('measured_depth_mm')} ({r.get('depth_status')}) | 槽宽均值 {r.get('measured_width_mm')} ({r.get('width_status')})" for r in reversed(rows)) if rows else "暂无历史记录。")
        layout.addWidget(text); dialog.exec()

    def show_output_path(self):
        OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
        try:
            os.startfile(str(OUTPUT_ROOT))
            self.log(f"已打开输出目录：{OUTPUT_ROOT}")
        except Exception as exc:
            QMessageBox.critical(self,"打开输出目录失败",f"无法打开输出目录：\n{OUTPUT_ROOT}\n\n{exc}")


def main() -> int:
    app = QApplication(sys.argv)
    app.setApplicationName("槽型深度宽度测量软件")
    window = SafeMainWindow(); window.show()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
